name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20"
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: css
          path: css/
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: css
          path: css/
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update CSS
          branch: gh-pages
